# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-14 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_cliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
